# Generated by Django 5.2.4 on 2026-07-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance',
            name='hostel_name',
            field=models.CharField(blank=True, help_text='Name of the hostel', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='grievance',
            name='hostel_room_no',
            field=models.CharField(blank=True, help_text='Hostel room number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='grievance',
            name='is_hosteler',
            field=models.BooleanField(default=False, help_text='Whether the student is a hosteler'),
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
