# Generated by Django 5.2.4 on 2026-09-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievances', '0002_grievance_hostel_name_grievance_hostel_room_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance',
            name='accumulated_sla_pause_minutes',
            field=models.IntegerField(default=0, help_text='Total minutes SLA was paused'),
        ),
        migrations.AddField(
            model_name='grievance',
            name='sla_pause_time',
            field=models.DateTimeField(blank=True, help_text='Time when status changed to pending_student', null=True),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('pending_student', 'Pending Student Reply'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
