# Generated by Django 5.2.4 on 2025-07-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievances', '0002_grievanceotpverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance',
            name='department',
            field=models.CharField(blank=True, help_text='Department related to grievance', max_length=100, null=True),
        ),
    ]
