# Generated by Django 5.2.4 on 2025-07-18 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grievances', '0003_grievance_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['category_type', 'name'], 'verbose_name_plural': 'Categories'},
        ),
    ]
