# Generated by Django 5.2.4 on 2026-09-18 21:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievances', '0003_grievance_accumulated_sla_pause_minutes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grievanceattachment',
            name='file',
            field=models.FileField(upload_to='grievance_attachments/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx', 'txt'])]),
        ),
    ]
