# Generated by Django 5.2.4 on 2025-07-18 17:42

from django.db import migrations


def convert_under_review_to_pending(apps, schema_editor):
    """Convert any existing 'under_review' status to 'pending'"""
    Grievance = apps.get_model('grievances', 'Grievance')
    Grievance.objects.filter(status='under_review').update(status='pending')


def reverse_convert_under_review_to_pending(apps, schema_editor):
    """Reverse operation - convert back to under_review if needed"""
    # We can't reliably reverse this, so we'll just pass
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('grievances', '0004_alter_category_options'),
    ]

    operations = [
        migrations.RunPython(
            convert_under_review_to_pending,
            reverse_convert_under_review_to_pending,
        ),
    ]
