# Generated by Django 5.2.4 on 2025-07-18 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievances', '0005_auto_20250718_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grievance',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
