# Generated by Django 5.2.4 on 2025-07-19 19:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievances', '0006_alter_grievance_status'),
        ('students', '0002_school_rename_course_studentprofile_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='auto_assign_enabled',
            field=models.BooleanField(default=True, help_text='Enable automatic assignment for this category'),
        ),
        migrations.CreateModel(
            name='CategoryAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('department', models.CharField(help_text='Department this assignment applies to', max_length=100)),
                ('school', models.CharField(blank=True, help_text='School this assignment applies to', max_length=200, null=True)),
                ('priority_level', models.IntegerField(default=1, help_text='Higher number = higher priority for matching')),
                ('is_active', models.BooleanField(default=True)),
                ('auto_assign_keywords', models.TextField(blank=True, help_text='Additional keywords for auto-assignment (comma-separated)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_assignments', to='students.adminprofile')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='grievances.category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority_level', 'category__name', 'department'],
                'unique_together': {('category', 'department', 'assigned_admin')},
            },
        ),
    ]
