# Generated by Django 5.2.4 on 2025-07-21 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grievances', '0007_category_auto_assign_enabled_categoryassignment'),
    ]

    operations = [
    ]
