# Generated by Django 5.2.4 on 2026-05-11 02:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievances', '0009_alter_auditlog_user_and_more'),
        ('students', '0006_remove_additional_department_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sla_hours',
            field=models.IntegerField(default=48, help_text='Service Level Agreement resolution time in hours'),
        ),
        migrations.AddField(
            model_name='grievance',
            name='escalation_level',
            field=models.IntegerField(default=0, help_text='0=Normal, 1=Admin, 2=Superadmin'),
        ),
        migrations.AddField(
            model_name='grievance',
            name='is_appealed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grievance',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Soft delete flag'),
        ),
        migrations.AddField(
            model_name='grievance',
            name='is_escalated',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('accepted', 'Appeal Accepted - Reopened'), ('rejected', 'Appeal Rejected - Closed')], default='pending', max_length=20)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grievance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='grievances.grievance')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.adminprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='students.studentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EscalationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('is_auto_escalated', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('escalated_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalated_from_logs', to='students.adminprofile')),
                ('escalated_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalated_to_logs', to='students.adminprofile')),
                ('grievance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalations', to='grievances.grievance')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeBaseArticle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('keywords', models.TextField(blank=True, help_text='Keywords to match for suggestion (comma-separated)', null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('view_count', models.IntegerField(default=0)),
                ('helpful_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='grievances.category')),
            ],
            options={
                'ordering': ['-view_count', '-created_at'],
            },
        ),
    ]
