# Generated by Django 5.2.4 on 2026-07-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('admin', 'Admin'), ('superadmin', 'Super Admin'), ('officer', 'Grievance Officer'), ('chief_warden', 'Chief Warden'), ('warden', 'Warden')], default='student', max_length=20),
        ),
    ]
