# Generated by Django 5.2.4 on 2026-09-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('admin', 'Admin'), ('superadmin', 'Super Admin'), ('officer', 'Grievance Officer')], default='student', max_length=20),
        ),
    ]
