# Generated by Django 5.2.4 on 2026-09-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Student'), ('admin', 'Admin'), ('superadmin', 'Super Admin'), ('officer', 'Grievance Officer')], max_length=20, unique=True)),
                ('permissions', models.JSONField(default=dict, help_text='JSON mapping of permission names to booleans')),
            ],
        ),
    ]
