# Generated by Django 5.2.4 on 2025-08-01 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_adminloginotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deactivation_reason',
            field=models.TextField(blank=True, help_text='Reason for account deactivation', null=True),
        ),
    ]
