# Generated by Django 5.2.4 on 2026-05-11 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(default='Student Grievance Management System', max_length=255)),
                ('contact_email', models.EmailField(default='admin@university.edu', max_length=254)),
                ('max_file_size', models.IntegerField(default=10, help_text='Max file size in MB')),
                ('email_notifications', models.BooleanField(default=True)),
                ('auto_assignment', models.BooleanField(default=True)),
                ('require_email_verification', models.BooleanField(default=True)),
                ('allow_student_registration', models.BooleanField(default=True)),
                ('session_timeout', models.IntegerField(default=60, help_text='Session timeout in minutes')),
                ('password_min_length', models.IntegerField(default=8)),
                ('default_priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('auto_resolve_days', models.IntegerField(default=30)),
                ('escalation_threshold', models.IntegerField(default=7)),
                ('allow_anonymous', models.BooleanField(default=False)),
                ('enable_auto_suggestions', models.BooleanField(default=True)),
                ('auto_categorize', models.BooleanField(default=True)),
                ('kb_confidence_score', models.IntegerField(default=80, help_text='Percentage 50-100')),
                ('max_reopen_count', models.IntegerField(default=2)),
                ('sla_breach_action', models.CharField(choices=[('notify', 'Notify Admin Only'), ('escalate', 'Auto-Escalate Immediately'), ('both', 'Notify & Auto-Escalate')], default='escalate', max_length=20)),
                ('require_closure_remark', models.BooleanField(default=True)),
                ('enable_feedback', models.BooleanField(default=True)),
                ('allow_attachments_in_replies', models.BooleanField(default=True)),
                ('support_hours', models.CharField(default='Mon-Fri, 9:00 AM - 5:00 PM', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
