# Generated by Django 5.2.4 on 2026-07-04 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsettings',
            name='enable_feedback',
        ),
    ]
