# Generated by Django 5.2.4 on 2026-09-18 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_systemsettings_allowed_email_domains'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsettings',
            name='auto_categorize',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='enable_auto_suggestions',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='kb_confidence_score',
        ),
    ]
