# Generated by Django 5.2.4 on 2026-09-19 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_remove_systemsettings_auto_categorize_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsettings',
            name='require_email_verification',
        ),
    ]
