# Generated by Django 5.2.4 on 2026-05-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
