# Generated by Django 5.2.4 on 2025-07-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_department_code_department_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofile',
            name='role_level',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Department Admin'), ('officer', 'Grievance Officer')], max_length=20),
        ),
    ]
