# Generated by Django 5.2.4 on 2025-07-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_adminprofile_role_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofile',
            name='department',
            field=models.CharField(default='General Department', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='school',
            field=models.CharField(default='General School', max_length=200),
        ),
    ]
