# Generated by Django 5.2.4 on 2026-09-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_adminprofile_role_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofile',
            name='role_level',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Department Admin'), ('officer', 'Grievance Officer')], max_length=20),
        ),
    ]
