# Generated by Django 5.2.4 on 2025-08-02 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_make_school_department_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='code',
        ),
        migrations.RemoveField(
            model_name='department',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='department',
            name='description',
        ),
        migrations.RemoveField(
            model_name='department',
            name='office_location',
        ),
        migrations.RemoveField(
            model_name='department',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='department',
            name='website',
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='department',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='school',
            field=models.CharField(max_length=200),
        ),
    ]
